package com.atitienei_daniel.recipe.domain.model

data class Recipe(
    val aggregateLikes: Int = 0,
    val analyzedInstructions: List<AnalyzedInstruction> = listOf(),
    val cheap: Boolean = false,
    val cookingMinutes: Int = 0,
    val creditsText: String? = null,
    val cuisines: List<String> = listOf(),
    val dairyFree: Boolean = false,
    val diets: List<String> = listOf(),
    val dishTypes: List<String> = listOf(),
    val extendedIngredients: List<ExtendedIngredient> = listOf(),
    val gaps: String = "",
    val glutenFree: Boolean = false,
    val healthScore: Int = 0,
    val id: Int = 0,
    val image: String? = null,
    val imageType: String? = null,
    val instructions: String = "",
    val license: String? = null,
    val lowFodmap: Boolean = false,
    val occasions: List<String> = listOf(),
    val openLicense: Int = 0,
    val originalId: Any? = null,
    val preparationMinutes: Int = 0,
    val pricePerServing: Double = 0.0,
    val readyInMinutes: Int = 0,
    val servings: Int = 0,
    val sourceName: String? = null,
    val sourceUrl: String = "",
    val spoonacularSourceUrl: String = "",
    val summary: String = "",
    val sustainable: Boolean = false,
    val title: String = "",
    val vegan: Boolean = false,
    val vegetarian: Boolean = false,
    val veryHealthy: Boolean = false,
    val veryPopular: Boolean = false,
    val weightWatcherSmartPoints: Int = 0
)